export const PERSONAL = {
  name: "Alex Chen",
  title: "Senior DevOps & Cloud Engineer",
  tagline: "Building infrastructure that never sleeps",
  email: "alex@alexchen.dev",
  github: "https://github.com/alexchen-dev",
  linkedin: "https://linkedin.com/in/alexchen-devops",
  twitter: "https://twitter.com/alexchen_dev",
  location: "San Francisco, CA",
  available: true,
  yearsExp: 8,
  bio: "I architect and automate cloud-native infrastructure at scale — turning complex distributed systems into reliable, self-healing platforms. Passionate about GitOps, infrastructure as code, and shifting security left.",
};

export const SKILLS = [
  { category: "Cloud Platforms", color: "#FF9900", items: [
    { name: "AWS", level: 95, icon: "aws" },
    { name: "GCP", level: 85, icon: "gcp" },
    { name: "Azure", level: 80, icon: "azure" },
  ]},
  { category: "Containers & Orchestration", color: "#326CE5", items: [
    { name: "Kubernetes", level: 95, icon: "k8s" },
    { name: "Docker", level: 98, icon: "docker" },
    { name: "Helm", level: 88, icon: "helm" },
    { name: "ArgoCD", level: 90, icon: "argocd" },
  ]},
  { category: "IaC & Config", color: "#7B42BC", items: [
    { name: "Terraform", level: 95, icon: "terraform" },
    { name: "Ansible", level: 88, icon: "ansible" },
    { name: "Pulumi", level: 75, icon: "pulumi" },
  ]},
  { category: "CI/CD", color: "#2088FF", items: [
    { name: "GitHub Actions", level: 95, icon: "github" },
    { name: "Jenkins", level: 85, icon: "jenkins" },
    { name: "GitLab CI", level: 82, icon: "gitlab" },
    { name: "Tekton", level: 75, icon: "tekton" },
  ]},
  { category: "Observability", color: "#E6522C", items: [
    { name: "Prometheus", level: 90, icon: "prometheus" },
    { name: "Grafana", level: 92, icon: "grafana" },
    { name: "Datadog", level: 85, icon: "datadog" },
    { name: "ELK Stack", level: 80, icon: "elastic" },
  ]},
  { category: "Languages", color: "#3776AB", items: [
    { name: "Python", level: 88, icon: "python" },
    { name: "Bash", level: 95, icon: "bash" },
    { name: "Go", level: 72, icon: "go" },
    { name: "TypeScript", level: 78, icon: "ts" },
  ]},
];

export const EXPERIENCE = [
  {
    company: "Stripe",
    role: "Staff DevOps Engineer",
    period: "2022 – Present",
    location: "San Francisco, CA",
    color: "#635BFF",
    achievements: [
      "Led migration of 200+ microservices to Kubernetes, reducing infra costs by 40%",
      "Built internal IDP using Backstage + Terraform that reduced onboarding time from 2 weeks to 2 hours",
      "Designed zero-downtime blue-green deployment pipeline processing $1B+ in daily transactions",
      "Reduced MTTR from 45 min to 8 min via AIOps-driven alerting and runbook automation",
    ],
    metrics: [{ label: "Cost Reduction", value: "40%" }, { label: "Services Migrated", value: "200+" }, { label: "Uptime SLA", value: "99.99%" }],
  },
  {
    company: "Databricks",
    role: "Senior Platform Engineer",
    period: "2020 – 2022",
    location: "San Francisco, CA",
    color: "#FF3621",
    achievements: [
      "Architected multi-cloud Terraform modules used across 50+ engineering teams",
      "Implemented GitOps with ArgoCD for 150+ Kubernetes applications across 5 clusters",
      "Built observability platform ingesting 2TB/day of metrics, logs, and traces",
      "Automated security compliance (SOC2, PCI-DSS) reducing audit prep from 3 months to 2 weeks",
    ],
    metrics: [{ label: "Teams Served", value: "50+" }, { label: "K8s Apps", value: "150+" }, { label: "Daily Metrics", value: "2TB" }],
  },
  {
    company: "Cloudflare",
    role: "DevOps Engineer",
    period: "2018 – 2020",
    location: "San Francisco, CA",
    color: "#F38020",
    achievements: [
      "Managed global edge infrastructure across 200+ PoPs worldwide",
      "Built chaos engineering framework reducing production incidents by 60%",
      "Containerized legacy monolith, enabling CI/CD and 10x faster deployments",
      "Automated DNS and certificate provisioning for 1M+ customer domains",
    ],
    metrics: [{ label: "PoPs Managed", value: "200+" }, { label: "Incident Reduction", value: "60%" }, { label: "Domains", value: "1M+" }],
  },
  {
    company: "Rackspace",
    role: "Cloud Infrastructure Engineer",
    period: "2016 – 2018",
    location: "Austin, TX",
    color: "#DC3545",
    achievements: [
      "Designed AWS landing zones for Fortune 500 enterprise clients",
      "Built Ansible playbooks automating OS hardening across 5,000+ servers",
      "Implemented AWS cost optimization saving clients $2M+ annually",
      "Migrated 30+ legacy apps to AWS, achieving 99.9% availability SLAs",
    ],
    metrics: [{ label: "Enterprise Clients", value: "20+" }, { label: "Servers Managed", value: "5K+" }, { label: "Cost Savings", value: "$2M+" }],
  },
];

export const PROJECTS = [
  {
    title: "K8s Multi-Cluster GitOps Platform",
    description: "Production-grade multi-cluster Kubernetes platform with ArgoCD, Crossplane, and automated policy enforcement across AWS, GCP, and Azure.",
    tags: ["Kubernetes", "ArgoCD", "Crossplane", "Terraform", "OPA"],
    color: "#22d3ee",
    icon: "cluster",
    metrics: ["5 clusters", "150+ apps", "99.99% uptime"],
    github: "https://github.com/alexchen-dev/k8s-gitops-platform",
    demo: "#",
  },
  {
    title: "Terraform AWS Landing Zone",
    description: "Enterprise AWS multi-account landing zone with Organizations, SSO, GuardDuty, Security Hub, and automated compliance checks.",
    tags: ["Terraform", "AWS", "Organizations", "GuardDuty", "Config"],
    color: "#a78bfa",
    icon: "terraform",
    metrics: ["50+ accounts", "SOC2 compliant", "CIS benchmarked"],
    github: "https://github.com/alexchen-dev/aws-landing-zone",
    demo: "#",
  },
  {
    title: "Zero-Trust CI/CD Security Pipeline",
    description: "SLSA Level 3 compliant CI/CD pipeline with SAST, SCA, container scanning, signed artifacts, and attestation using Sigstore/Cosign.",
    tags: ["GitHub Actions", "Sigstore", "Trivy", "SLSA", "OIDC"],
    color: "#34d399",
    icon: "shield",
    metrics: ["SLSA L3", "100% signed", "0 CVE escapes"],
    github: "https://github.com/alexchen-dev/zero-trust-cicd",
    demo: "#",
  },
  {
    title: "Observability Stack",
    description: "Full-stack observability platform using the OpenTelemetry collector, Prometheus, Loki, Tempo, and Grafana with automated SLO dashboards.",
    tags: ["OpenTelemetry", "Prometheus", "Grafana", "Loki", "Tempo"],
    color: "#fb923c",
    icon: "monitor",
    metrics: ["2TB/day", "P99 < 100ms alerts", "Auto-SLO"],
    github: "https://github.com/alexchen-dev/otel-observability",
    demo: "#",
  },
  {
    title: "Kubernetes Cost Optimizer",
    description: "Python-based K8s cost optimization tool using Vertical and Horizontal Pod Autoscaler recommendations with Spot instance management.",
    tags: ["Python", "Kubernetes", "VPA", "HPA", "Spot"],
    color: "#f472b6",
    icon: "cost",
    metrics: ["35% cost saved", "Auto-rightsizing", "Spot 80%"],
    github: "https://github.com/alexchen-dev/k8s-cost-optimizer",
    demo: "#",
  },
  {
    title: "Chaos Engineering Framework",
    description: "Custom chaos engineering tool built on LitmusChaos and Chaos Monkey principles with automated game days and resilience scoring.",
    tags: ["LitmusChaos", "Python", "Kubernetes", "Prometheus", "Go"],
    color: "#ef4444",
    icon: "chaos",
    metrics: ["60% fewer incidents", "30+ scenarios", "Auto gamedays"],
    github: "https://github.com/alexchen-dev/chaos-framework",
    demo: "#",
  },
];

export const CERTIFICATIONS = [
  { name: "AWS Solutions Architect Professional", issuer: "Amazon Web Services", year: "2023", badge: "aws-sap", color: "#FF9900" },
  { name: "AWS DevOps Engineer Professional", issuer: "Amazon Web Services", year: "2022", badge: "aws-dop", color: "#FF9900" },
  { name: "Certified Kubernetes Administrator", issuer: "CNCF", year: "2023", badge: "cka", color: "#326CE5" },
  { name: "Certified Kubernetes Security Specialist", issuer: "CNCF", year: "2023", badge: "cks", color: "#326CE5" },
  { name: "HashiCorp Terraform Associate", issuer: "HashiCorp", year: "2022", badge: "terraform", color: "#7B42BC" },
  { name: "Azure DevOps Expert", issuer: "Microsoft", year: "2023", badge: "azure", color: "#0078D4" },
  { name: "GCP Professional DevOps Engineer", issuer: "Google Cloud", year: "2022", badge: "gcp", color: "#4285F4" },
  { name: "Certified Kubernetes App Developer", issuer: "CNCF", year: "2021", badge: "ckad", color: "#326CE5" },
];

export const BLOG_POSTS = [
  {
    title: "Building a Production-Grade GitOps Platform with ArgoCD and Crossplane",
    excerpt: "How we replaced 10,000 lines of Helm charts with a declarative, self-healing platform that provisions everything from databases to DNS records.",
    date: "Dec 10, 2024",
    readTime: "12 min",
    tags: ["GitOps", "ArgoCD", "Crossplane"],
    color: "#22d3ee",
  },
  {
    title: "Zero-Trust Kubernetes: Security from the Container Runtime Up",
    excerpt: "A deep dive into building a zero-trust architecture for Kubernetes using Cilium, OPA Gatekeeper, Falco, and Sigstore.",
    date: "Nov 22, 2024",
    readTime: "15 min",
    tags: ["Security", "Kubernetes", "Zero-Trust"],
    color: "#a78bfa",
  },
  {
    title: "Terraform at Scale: Managing 50+ AWS Accounts Without Going Insane",
    excerpt: "Lessons learned managing a Terraform monorepo for 50+ AWS accounts — from state locking nightmares to Atlantis-driven PR workflows.",
    date: "Oct 15, 2024",
    readTime: "10 min",
    tags: ["Terraform", "AWS", "IaC"],
    color: "#34d399",
  },
];

export const TERMINAL_LINES = [
  { text: "$ kubectl get nodes -o wide", delay: 0 },
  { text: "NAME                STATUS   ROLES    AGE   VERSION", delay: 600, dim: true },
  { text: "node-prod-1a        Ready    master   42d   v1.29.0", delay: 800, dim: true },
  { text: "node-prod-1b        Ready    worker   42d   v1.29.0", delay: 1000, dim: true },
  { text: "node-prod-1c        Ready    worker   42d   v1.29.0", delay: 1200, dim: true },
  { text: "", delay: 1400 },
  { text: "$ terraform apply --auto-approve", delay: 1600 },
  { text: "Plan: 12 to add, 3 to change, 0 to destroy.", delay: 2200, color: "#22d3ee", dim: true },
  { text: "Apply complete! Resources: 12 added, 3 changed.", delay: 3800, color: "#34d399", dim: true },
  { text: "", delay: 4000 },
  { text: "$ docker build -t api:v2.4.1 --push .", delay: 4200 },
  { text: "Successfully pushed sha256:a1b2c3d4e5f6", delay: 5800, color: "#34d399", dim: true },
  { text: "", delay: 6000 },
  { text: "$ argocd app sync production --prune", delay: 6200 },
  { text: "✓  deployment/api   Synced   Healthy", delay: 7400, color: "#34d399", dim: true },
  { text: "✓  service/api      Synced   Healthy", delay: 7600, color: "#34d399", dim: true },
];
